### ISSUE TITLE
Вывод сдававших аттестацию по городу.

### ISSUE THREAD

**Issue by bodhij** [hda-technical/attestations_wordpress_plugin#2]
Было бы здорово, если бы была возможность вывести сдавших аттестацию в конкретном городе. Сейчас справа от каждой фамилии стоит текст вида "(город)". Его можно сделать ссылкой, которая бы выдавала список сдававших по городу.

**Comment by rkond** [comment]
Тогда хорошо бы сделать еще список городов. Это не очень сложно, сделаю при случае.

**Comment by bodhij** [comment]
Это не обязательно, т.к. поле "город" выводится рядом с именем, но ты прав - было бы хорошо.

**Comment by rkond** [comment]
Сделано
