### ISSUE TITLE
Показ сданных уровней.

### ISSUE THREAD

**Issue by bodhij** [hda-technical/attestations_wordpress_plugin#3]
Хочется сразу видеть, какие уровни человек имеет, при просмотре общего списка. Достаточно текущих.

**Comment by rkond** [comment]
При текущей системе это чересчур затратно, каждого человека обсчитывать индивидуально. Поясни кейс, когда и зачем это нужно?

**Comment by bodhij** [comment]
Это удобно в любых случаях, когда нужно быстро получить информацию об уровне большого числа людей. Например, при массовой сдаче аттестации, или как у нас на конференции, от уровня зависит скидка. Другой аргумент - косвенный: часто база аттестации просматривается с телефона, а шрифт мелкий, и вряд ли разумно его увеличивать. Было бы удобнее сразу видеть текущий уровень сдающего.

**Comment by rkond** [comment]
Можно сделать так, чтобы имя по щелчку рачкрывалось в полную карточку. И потом закрывалось обратно по щелчку. Устроит?

**Comment by bodhij** [comment]
Очень круто. Устроит

**Comment by rkond** [comment]
Сделано
