### ISSUE TITLE
Редактирование аттестации конкретного человека.

### ISSUE THREAD

**Issue by bodhij** [hda-technical/attestations_wordpress_plugin#4]
Хотелось бы иметь возможность не только добавлять, но и редактировать и удалять аттестацию, т.к. возможны ошибки. При этом желательно вести логирование таких операций.

**Comment by rkond** [comment]
Тебя устроит, если редактирования не будет, но можно будет удалить? Логи на все это делать немного лень, но я попробую.

**Comment by bodhij** [comment]
Да, устроит.

**Comment by rkond** [comment]
Сделана страница с историей записей об аттестации
