### ISSUE TITLE
Кривая вёрстка

### ISSUE THREAD

**Issue by lapsh** [hda-technical/attestations_wordpress_plugin#7]
При просмотре деталей присвоенных уровней по одному человеку в мобильной версии показывает только левые 50% страницы с информацией без полосы прокрутки и без возможности уменьшить масштаб, чтобы посмотреть всё. Chrome mobile 67.0.3396.68

Та же проблема на списке аттестованных людей, но там не мешает.

**Comment by rkondratenko** [comment]
![image](https://user-images.githubusercontent.com/13419095/41157067-0eeee96e-6b2d-11e8-8e5e-938f9d544a7e.png)
